version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../:/app
      - model-data:/app/models
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - MONGODB_DB=arxiv_assistant
      - MODEL_PATH=/app/models/llama-3.1-8b-quantized
    depends_on:
      - mongodb
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=arxiv_assistant

  ui:
    build:
      context: ../ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../ui:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - app

volumes:
  mongodb-data:
  model-data:
