# Model Configuration

# Model configuration
model:
  # Base model
  base_model_id: "mistralai/Mistral-7B-v0.1"
  # Fine-tuned model path (will be created during fine-tuning)
  fine_tuned_model_path: "models/mistral-7b-arxiv-finetuned"
  # Quantization settings
  quantization:
    method: "bitsandbytes"  # Options: bitsandbytes, llama.cpp, gptq
    bits: 4  # Options: 4, 8
    group_size: 128  # For GPTQ

  # Generation settings
  generation:
    max_new_tokens: 512
    temperature: 0.7
    top_p: 0.9
    top_k: 40
    repetition_penalty: 1.1
    do_sample: true

  # Context window settings
  context_window:
    max_length: 4096
    truncation_strategy: "sliding_window"  # Options: sliding_window, start, end
    stride: 512

  # Fine-tuning settings
  fine_tuning:
    train_batch_size: 4
    eval_batch_size: 4
    num_train_epochs: 3
    learning_rate: 2e-5
    warmup_steps: 500
    weight_decay: 0.01
    gradient_accumulation_steps: 8
    max_grad_norm: 1.0
    logging_steps: 10
    save_steps: 500
    eval_steps: 500

# Embedding model configuration
embedding:
  model_id: "sentence-transformers/all-mpnet-base-v2"
  dimension: 768
  batch_size: 32
  normalize: true
  pooling: "mean"  # Options: mean, max, cls
  device: "cuda"  # Options: cuda, cpu

# RAG configuration
rag:
  retrieval:
    top_k: 5
    similarity_threshold: 0.7
    reranking: true
    hybrid_search: true
    keyword_weight: 0.3
    semantic_weight: 0.7

  prompt_template: |
    You are a Computer Science expert assistant that helps users with their research questions.
    Use the following pieces of context to answer the question at the end.
    If you don't know the answer, just say that you don't know, don't try to make up an answer.
    Always cite the source of your information using the paper ID provided in the context.

    Context:
    {context}

    Question: {question}

    Answer:

  system_prompt: |
    You are a helpful, harmless, and honest AI assistant specialized in Computer Science research.
    You have access to a database of arXiv papers in the Computer Science domain.
    When answering questions, cite relevant papers and explain concepts clearly.
    If you're unsure about something, acknowledge your uncertainty rather than making up information.
